(function(){
  'use strict';
  const F=BostonFinance, el=id=>document.getElementById(id), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), money=n=>Number(n).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  let endpoint=localStorage.getItem('boston-finance-endpoint')||window.BostonFinanceConfig?.apiUrl||'', data=null, busy=false, loaded=false, selectedReceipt=null;
  const demo=location.hostname==='127.0.0.1'&&new URLSearchParams(location.search).has('financeDemo');
  if(demo)endpoint='/finance-api';
  async function api(action,payload){if(!endpoint)throw Error('ยังไม่ได้เชื่อม Apps Script การเงินชุดใหม่ กรุณาตั้งค่า URL ด้านล่าง');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload}),signal:controller.signal,redirect:'follow'});if(!r.ok)throw Error('เชื่อมต่อไม่สำเร็จ HTTP '+r.status);let result;try{result=await r.json();}catch{throw Error('URL นี้ไม่ได้ตอบข้อมูลการเงิน กรุณาตรวจสอบ deployment');}if(!result.success){const error=Error(result.message||'ทำรายการไม่สำเร็จ');error.code=result.code;throw error;}return result;}catch(e){if(e.name==='AbortError')throw Error('ยังยืนยันผลไม่ได้ กรุณาลองซ้ำด้วยแบบฟอร์มเดิม ระบบจะใช้รหัสคำขอเดิมป้องกันรายการซ้ำ');throw e;}finally{clearTimeout(timer);}}
  function message(text,error=false){el('fin-status').textContent=text;el('fin-status').className='fin-banner'+(error?' error':'');el('rec-status').textContent=text;}
  async function load(){if(busy)return;busy=true;message('กำลังโหลดรายการการเงินและใบเสร็จ…');try{data=await api('getFinance');loaded=true;render();renderReceipts();message(demo?'ข้อมูลตัวอย่างสำหรับทดสอบ — ไม่ใช่ยอดเงินจริง':'โหลดข้อมูลล่าสุดแล้ว • คำนวณถึงวันนี้ตามเวลาไทย');}catch(e){message(e.message,true);}finally{busy=false;}}
  function groupHTML(groups,total,color){return groups.length?groups.map(g=>`<div class="fin-category"><div><span>${E(g.label)}</span><strong>${money(g.amount)} ฿</strong></div><div class="fin-track"><span style="width:${total?g.amount/total*100:0}%;background:${color}"></span></div></div>`).join(''):'<p class="fin-empty">ไม่มีรายการ</p>';}
  function render(){if(!data)return;const month=el('fin-all-time').checked?'':el('fin-month').value, m=F.summarize(data.transactions,month,today());
    el('fin-cards').innerHTML=[['income','รายรับ',m.income],['expense','รายจ่าย',m.expense],['net',m.net<0?'รายจ่ายเกินรายรับ':'ส่วนต่างรายรับ–รายจ่าย',m.net]].map(([cls,label,n])=>`<div class="fin-card ${cls}"><span>${label}</span><strong>${money(n)} ฿</strong><small class="fin-muted">${month?E(month):'รวมทุกเดือนที่มีข้อมูล'}${month===today().slice(0,7)?' • ถึงวันนี้':''}</small></div>`).join('');
    el('fin-income-groups').innerHTML=groupHTML(m.incomeGroups,m.income,'#139d86');el('fin-expense-groups').innerHTML=groupHTML(m.expenseGroups,m.expense,'#e78972');
    el('fin-advice').innerHTML=m.advice.map(s=>`<p class="fin-insight">${E(s)}</p>`).join('')+(m.invalidCount?`<p class="fin-error">ไม่นับ ${m.invalidCount} รายการที่ข้อมูลไม่สมบูรณ์หรือรหัสซ้ำ กรุณาตรวจในชีต</p>`:'');
    el('fin-lifetime').innerHTML=`<p class="fin-muted">${m.firstDate?'ตั้งแต่รายการแรก '+E(m.firstDate)+' ถึง '+E(today()):'ยังไม่มีรายการ'} • ไม่รวมข้อมูลในชีตสำรอง</p><div class="fin-all"><div>รายรับสะสม<strong>${money(m.all.income)} ฿</strong></div><div>รายจ่ายสะสม<strong>${money(m.all.expense)} ฿</strong></div><div>ส่วนต่างสะสม<strong>${money(m.all.net)} ฿</strong></div></div>`;
    const series=m.monthly.slice(-12),max=Math.max(1,...series.flatMap(r=>[r.income,r.expense]));
    el('fin-chart').innerHTML=series.length?series.map(r=>`<div class="fin-month"><div class="fin-bars"><span class="fin-income" style="height:${r.income/max*160}px" title="รายรับ ${money(r.income)}"></span><span class="fin-expense" style="height:${r.expense/max*160}px" title="รายจ่าย ${money(r.expense)}"></span></div><strong>${E(r.month)}</strong><div>${money(r.net)} ฿</div></div>`).join(''):'<p class="fin-empty">ยังไม่มีข้อมูลสำหรับกราฟ</p>';
    el('fin-month-table').innerHTML=m.monthly.map(r=>`<tr><td>${E(r.month)}</td><td>${money(r.income)}</td><td>${money(r.expense)}</td><td>${money(r.net)}</td></tr>`).join('');
    const query=el('fin-search').value.trim().toLowerCase();el('fin-transactions').innerHTML=m.selected.filter(r=>[r.note,r.category,r.reference].join(' ').toLowerCase().includes(query)).map(r=>`<tr><td>${E(r.date)}</td><td>${r.type==='income'?'รายรับ':'รายจ่าย'}</td><td>${E(F.categories[r.category]||r.category)}</td><td>${E(r.note)}</td><td>${money(r.amount)}</td><td>${E(r.payment_method||'ไม่ระบุ')}</td><td>${E(r.reference)}</td></tr>`).join('')||'<tr><td colspan="7" class="fin-empty">ไม่มีรายการที่ตรงกับเงื่อนไข</td></tr>';
  }
  function input(name,label,type='text',value='',required=false){return `<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${required?'required':''} ${type==='number'?'min="0" max="10000000000" step="0.01"':''} ${type==='date'?`max="${today()}"`:''}></label>`;}
  function payment(name){return `<label>ช่องทางชำระเงิน<select name="${name}"><option>โอนเงิน</option><option>เงินสด</option><option>บัตร</option><option>อื่นๆ</option></select></label>`;}
  function openForm(kind){if(!loaded){message('กรุณาเชื่อมต่อและโหลดข้อมูลก่อนบันทึก',true);return;}const receipt=kind==='receipt',form=el('fin-form');el('fin-form-title').textContent=receipt?'ออกใบเสร็จรับเงิน':'เพิ่มรายการเงินเข้า / ออก';
    form.innerHTML=receipt?`<label class="fin-wide">เลือกการลงทะเบียน (หรือกรอกข้อมูลเอง)<select id="rec-enrollment"><option value="">กรอกข้อมูลเอง</option>${typeof state!=='undefined'?state.enrollments.map(r=>{const s=state.students.find(s=>s.StudentID===r.StudentID);return `<option value="${E(r.EnrollmentID)}">${E(s?.Nickname||s?.StudentName||r.StudentID)} • ${E(r.Course)} / ${E(r.Level)}</option>`;}).join(''):''}</select></label>${input('StudentName','ชื่อนักเรียน','text','',true)}${input('ParentName','ชื่อผู้ปกครอง')}${input('CourseLevel','หลักสูตร','text','',true)}${input('Level','Level')}${input('CourseDetail','รายละเอียดหลักสูตร')}${input('ReceiptDate','วันที่รับเงิน','date',today(),true)}${input('CoursePrice','ค่าเรียน (บาท)','number',0,true)}${input('AddOnItem','รายการเพิ่มเติม')}${input('AddOnPrice','ราคาเพิ่มเติม (บาท)','number',0,true)}${input('Discount','ส่วนลด (บาท)','number',0,true)}${payment('PaymentMethod')}<p id="rec-total" class="fin-total">ยอดสุทธิ 0.00 ฿</p><p class="fin-wide fin-muted">บันทึกเมื่อรับเงินจริงแล้ว ระบบจะสร้างรายรับอัตโนมัติ ใบเสร็จที่บันทึกแล้วไม่สามารถแก้ไขจากหน้านี้</p>`:`${input('date','วันที่รับ / จ่ายจริง','date',today(),true)}<label>ประเภท<select name="type"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select></label><label>หมวด<select name="category" id="fin-category"></select></label>${input('amount','จำนวนเงิน (บาท)','number','',true)}${payment('payment_method')}${input('reference','เลขอ้างอิง (ถ้ามี)')}<label class="fin-wide">รายละเอียด<textarea name="note" maxlength="2000"></textarea></label>`;
    const pendingKey='boston-finance-pending-'+kind; let pending=null; try{pending=JSON.parse(localStorage.getItem(pendingKey)||'null');}catch{} let requestId=pending?.RequestID||pending?.id||crypto.randomUUID(),studentId='',enrollmentId='';
    if(receipt){el('rec-enrollment').onchange=e=>{const r=state.enrollments.find(r=>r.EnrollmentID===e.target.value);if(!r){studentId='';enrollmentId='';return;}const s=state.students.find(s=>s.StudentID===r.StudentID);studentId=r.StudentID;enrollmentId=r.EnrollmentID;Object.entries({StudentName:s?.StudentName||s?.Nickname||'',ParentName:s?.ParentName||'',CourseLevel:r.Course,Level:r.Level}).forEach(([k,v])=>form.elements[k].value=v);};form.oninput=()=>{try{el('rec-total').textContent='ยอดสุทธิ '+money(F.receiptTotal(Object.fromEntries(new FormData(form))))+' ฿';}catch{el('rec-total').textContent='กรุณาตรวจสอบยอดเงินและส่วนลด';}};}else{const categories=()=>el('fin-category').innerHTML=Object.entries(F.categories).filter(([k])=>form.elements.type.value==='income'?k.startsWith('income'):k.startsWith('exp')).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');form.elements.type.onchange=categories;categories();form.oninput=null;}
    if(pending){Object.entries(pending).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v;});form.querySelectorAll('input,select,textarea').forEach(i=>i.disabled=true);} el('fin-form-error').textContent=pending?'มีคำขอที่ยังไม่ยืนยันผล กดบันทึกเพื่อตรวจสอบและทำคำขอเดิมให้ครบ โดยไม่สร้างซ้ำ':'';el('fin-save').disabled=false;el('fin-dialog').showModal();form.onsubmit=async e=>{e.preventDefault();if(busy)return;const payload=pending||Object.fromEntries(new FormData(form));if(!pending)Object.assign(payload,receipt?{RequestID:requestId,StudentID:studentId,EnrollmentID:enrollmentId}:{id:requestId});try{if(receipt){F.receiptTotal(payload);if(!payload.StudentName.trim()||!payload.CourseLevel.trim())throw Error('กรุณากรอกชื่อนักเรียนและหลักสูตร');}else if(F.cents(payload.amount)<=0)throw Error('จำนวนเงินต้องมากกว่า 0');if(Object.values(payload).some(v=>String(v).length>2000))throw Error('ข้อความยาวเกิน 2000 ตัวอักษร');}catch(e){el('fin-form-error').textContent=e.message;return;} busy=true;localStorage.setItem(pendingKey,JSON.stringify(payload));el('fin-save').disabled=true;el('fin-cancel').disabled=true;try{const result=await api(receipt?'saveReceipt':'saveTransaction',payload);localStorage.removeItem(pendingKey);el('fin-dialog').close();busy=false;await load();if(receipt){selectedReceipt=result.data;try{await showReceipt(selectedReceipt);}catch(previewError){message('บันทึกใบเสร็จแล้ว แต่สร้างรูปภาพไม่สำเร็จ กรุณากดดู / ดาวน์โหลด PNG อีกครั้ง',true);}}}catch(error){if(error.code==='VALIDATION_ERROR'){pending=null;localStorage.removeItem(pendingKey);form.querySelectorAll('input,select,textarea').forEach(i=>i.disabled=false);el('fin-form-error').textContent=error.message;}else{pending=payload;form.querySelectorAll('input,select,textarea').forEach(i=>i.disabled=true);el('fin-form-error').textContent=error.message+' • เก็บคำขอเดิมไว้แล้ว กดบันทึกเพื่อลองคำขอเดิมอีกครั้ง';}}finally{busy=false;el('fin-save').disabled=false;el('fin-cancel').disabled=false;}};
  }
  function renderReceipts(){if(!data)return;el('rec-list').innerHTML=data.receipts.slice().reverse().map(r=>`<tr><td>${E(r.ReceiptNo)}</td><td>${E(r.ReceiptDate)}</td><td>${E(r.StudentName)}</td><td>${E(r.CourseLevel)}</td><td>${money(r.NetTotal)}</td><td><button class="btn btn-secondary" data-receipt="${E(r.ReceiptNo)}">ดู / ดาวน์โหลด PNG</button></td></tr>`).join('')||'<tr><td colspan="6">ยังไม่มีใบเสร็จ</td></tr>';el('rec-list').querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>showReceipt(data.receipts.find(r=>r.ReceiptNo===b.dataset.receipt)).catch(e=>message(e.message,true)));}
  async function showReceipt(r){selectedReceipt=r;await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1170;const ctx=canvas.getContext('2d');
    const lines=(text,width,size)=>{ctx.font=`${size}px Kanit, sans-serif`;const result=[];let line='';for(const ch of Array.from(String(text||''))){if(ctx.measureText(line+ch).width>width&&line){result.push(line);line=ch;}else line+=ch;}if(line)result.push(line);return result;};
    const body=[['ได้รับเงินจาก',r.StudentName],['ผู้ปกครอง',r.ParentName],['หลักสูตร / Level',r.CourseLevel+' / '+(r.Level||'-')],['รายละเอียด',r.CourseDetail],['รายการเพิ่มเติม',[r.AddOnItem,r.AddOnDetail].filter(Boolean).join(' • ')]].filter(([,v])=>v);const rows=body.map(([k,v])=>({k,lines:lines(v,970,34)}));canvas.height=1030+rows.reduce((n,r)=>n+75+r.lines.length*46,0);ctx.fillStyle='#f2f7fb';ctx.fillRect(0,0,1170,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(35,35,1100,canvas.height-70);ctx.fillStyle='#078cbb';ctx.fillRect(35,35,1100,12);
    function text(t,x,y,size=30,color='#173451',align='left'){ctx.font=`${size}px Kanit,sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(String(t),x,y);}
    const logo=new Image();logo.src='assets/boston-logo.png';await logo.decode();const lh=800*logo.height/logo.width;ctx.drawImage(logo,185,75,800,lh);let y=95+lh;text('ใบเสร็จรับเงิน / RECEIPT',585,y+60,46,'#173451','center');text(r.ReceiptNo,585,y+110,32,'#078cbb','center');text('วันที่ '+r.ReceiptDate+' • '+(r.Status||'ออกใบเสร็จแล้ว'),585,y+155,27,'#62758a','center');y+=220;
    rows.forEach(row=>{text(row.k,100,y,25,'#62758a');y+=45;row.lines.forEach(line=>{text(line,100,y,34);y+=46;});y+=30;});
    [['ค่าเรียน',r.CoursePrice],['รายการเพิ่มเติม',r.AddOnPrice],['ส่วนลด',r.Discount]].forEach(([k,v])=>{text(k,100,y);text(money(v)+' ฿',1070,y,32,'#173451','right');y+=52;});ctx.fillStyle='#078cbb';ctx.fillRect(80,y,1010,96);text('ยอดสุทธิ',110,y+62,36,'white');text(money(r.NetTotal)+' ฿',1060,y+62,42,'white','right');y+=150;
    text('BostonRobotics Learning Center',585,y,30,'#173451','center');text('940 Anangkhanat Rd., Mueang Kalasin, Kalasin 46000',585,y+45,24,'#62758a','center');text('Tel. 095-663-0891 • Tax ID: 1460900048314',585,y+85,24,'#62758a','center');
    el('rec-preview').replaceChildren(canvas);el('rec-download').hidden=false;el('rec-download').onclick=()=>canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=r.ReceiptNo+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);},'image/png');
  }
  document.addEventListener('DOMContentLoaded',()=>{
    el('finance').innerHTML=`<div class="fin-head"><div><h1>รายงานการเงิน</h1><p class="fin-muted">BostonRobotics • ติดตามเงินเข้า เงินออก และวางแผนเดือนถัดไป</p></div><button id="fin-add" class="btn btn-primary">+ เพิ่มรายรับ / รายจ่าย</button></div><div class="fin-toolbar"><input id="fin-month" aria-label="เดือนที่ต้องการดู" type="month" value="${today().slice(0,7)}"><label><input id="fin-all-time" type="checkbox"> ทุกเดือน</label><button id="fin-refresh" class="btn btn-secondary">โหลดข้อมูลล่าสุด</button></div><p id="fin-status" class="fin-banner">ยังไม่ได้โหลดข้อมูลการเงิน</p><div id="fin-cards" class="fin-cards"></div><div class="fin-panel"><h2>แนวโน้มรายเดือน</h2><p class="fin-muted">12 เดือนล่าสุดที่มีข้อมูล • สีเขียว = รายรับ / สีส้ม = รายจ่าย • ตัวเลขใต้กราฟ = ส่วนต่าง</p><div id="fin-chart" class="fin-chart" role="img" aria-label="เปรียบเทียบรายรับรายจ่ายรายเดือน รายละเอียดตัวเลขอยู่ในตารางด้านล่าง"></div><details><summary>ดูตัวเลขรายเดือนทั้งหมด</summary><div class="fin-scroll"><table class="fin-table"><thead><tr><th>เดือน</th><th>รายรับ</th><th>รายจ่าย</th><th>ส่วนต่าง</th></tr></thead><tbody id="fin-month-table"></tbody></table></div></details></div><div class="fin-grid"><div class="fin-panel"><h2>รายรับมาจากอะไร</h2><div id="fin-income-groups"></div></div><div class="fin-panel"><h2>รายจ่ายไปกับอะไร</h2><div id="fin-expense-groups"></div></div></div><div class="fin-panel"><h2>วิเคราะห์และแนวทางเบื้องต้น</h2><div id="fin-advice"></div><p class="fin-muted fin-note">วิเคราะห์จากรายการรับ–จ่ายที่บันทึกและมีสถานะ active เท่านั้น ส่วนต่างนี้ไม่ใช่กำไรสุทธิทางบัญชี และไม่รวมลูกหนี้ เจ้าหนี้ ค่าเสื่อมราคา หรือภาษีที่ยังไม่ได้บันทึก</p></div><div class="fin-panel" style="margin-top:18px"><h2>ภาพรวมสะสมของสถาบัน</h2><div id="fin-lifetime"></div><p class="fin-muted">หากข้อมูลก่อนวันแรกยังไม่ถูกบันทึก ยอดนี้จะยังไม่ครอบคลุมตั้งแต่วันเปิดสถาบัน</p></div><div class="fin-panel" style="margin-top:18px"><div class="fin-head"><h2>รายการในช่วงที่เลือก</h2><input id="fin-search" class="input-form" placeholder="ค้นหารายละเอียด / เลขอ้างอิง" aria-label="ค้นหารายการการเงิน"></div><div class="fin-scroll"><table class="fin-table"><thead><tr><th>วันที่</th><th>ประเภท</th><th>หมวด</th><th>รายละเอียด</th><th>บาท</th><th>ชำระผ่าน</th><th>อ้างอิง</th></tr></thead><tbody id="fin-transactions"></tbody></table></div></div><details class="fin-config"><summary>ตั้งค่าการเชื่อมต่อระบบการเงินใหม่</summary><p class="fin-muted">ใช้ URL /exec ของ Apps Script ชุดใหม่จาก apps-script/finance/Code.gs การตั้งค่านี้บันทึกเฉพาะเบราว์เซอร์นี้</p><div class="fin-toolbar"><input id="fin-url" type="url" aria-label="URL Apps Script การเงิน" placeholder="https://script.google.com/macros/s/…/exec" value="${E(demo?'':endpoint)}"><button id="fin-connect" class="btn btn-primary">บันทึก URL และเชื่อมต่อ</button></div></details>`;
    el('receipts').innerHTML=`<div class="fin-head"><div><h1>ใบเสร็จรับเงิน</h1><p class="fin-muted">รับเงินแล้ว • สร้างรายรับอัตโนมัติ • ดาวน์โหลด PNG ส่งผู้ปกครอง</p></div><button id="rec-add" class="btn btn-primary">+ ออกใบเสร็จ</button></div><p id="rec-status" class="fin-banner">เชื่อมต่อผ่านการตั้งค่าในแท็บรายงานการเงิน</p><div class="fin-panel fin-scroll"><table class="fin-table"><thead><tr><th>เลขที่</th><th>วันที่</th><th>นักเรียน</th><th>หลักสูตร</th><th>ยอดสุทธิ</th><th>รูปภาพ</th></tr></thead><tbody id="rec-list"></tbody></table></div><div class="fin-actions"><button id="rec-download" class="btn btn-primary" hidden>ดาวน์โหลด PNG</button></div><div id="rec-preview" class="receipt-preview"></div><p class="fin-muted">ใบเสร็จรูปภาพยังไม่มีลายเซ็นหรือตราประทับ จนกว่าจะมีไฟล์ต้นฉบับที่ต้องการใช้</p>`;
    const dialog=document.createElement('dialog');dialog.id='fin-dialog';dialog.className='fin-dialog';dialog.innerHTML='<h2 id="fin-form-title"></h2><form id="fin-form" class="fin-form"></form><p id="fin-form-error" class="fin-error" role="alert"></p><div class="fin-actions"><button type="button" id="fin-cancel" class="btn btn-secondary">ปิด</button><button id="fin-save" form="fin-form" class="btn btn-primary">บันทึก</button></div>';document.body.append(dialog);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});el('fin-cancel').onclick=()=>dialog.close();el('fin-add').onclick=()=>openForm('transaction');el('rec-add').onclick=()=>openForm('receipt');el('fin-month').onchange=render;el('fin-all-time').onchange=()=>{el('fin-month').disabled=el('fin-all-time').checked;render();};el('fin-search').oninput=render;el('fin-refresh').onclick=load;
    el('fin-connect').onclick=()=>{const url=el('fin-url').value.trim();if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(url)){message('กรุณาใช้ URL Apps Script ที่ลงท้าย /exec',true);return;}endpoint=url;localStorage.setItem('boston-finance-endpoint',url);data=null;loaded=false;load();};
    document.querySelectorAll('[data-target="finance"],[data-target="receipts"]').forEach(b=>b.addEventListener('click',()=>{if(!loaded)load();}));
  });
})();
