// BostonRobotics Finance API 1.0. Deploy as a NEW standalone Apps Script project.
// Passwordless access is intentional, as requested by the owner.
const FINANCE_DB='1OSrFdehq7o1IrASmkTcbtSylCo49erUyzn_xCAJnn9Q';
const RECEIPT_DB='1t4tLaAS4sYRtVZ4podFh1OdSaqnqzAtJBVR7whetJ-Q';
const TX_HEADERS=['date','type','category','amount','note','id','status','created_at','updated_at','updated_by','payment_method','reference','attachment_url','revision','history_json'];
const RECEIPT_HEADERS=['Timestamp','ReceiptNo','StudentName','ParentName','CourseLevel','CourseDetail','CoursePrice','AddOnItem','AddOnDetail','AddOnPrice','Discount','NetTotal','ReceiptDate','Status','RequestID','StudentID','EnrollmentID','Level','PaymentMethod','TransactionID'];
function json_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
function doGet(){return json_({success:true,service:'boston-finance',version:'1.0',authMode:'none'});}
function doPost(e){try{const r=JSON.parse(e.postData.contents);if(r.action==='getFinance')return json_({success:true,transactions:read_(FINANCE_DB,'Transactions',TX_HEADERS),receipts:read_(RECEIPT_DB,'Data1',RECEIPT_HEADERS.slice(0,14))});
  const lock=LockService.getScriptLock();if(!lock.tryLock(20000))throw Error('มีรายการกำลังบันทึก กรุณาลองใหม่');
  try {let result;if(r.action==='saveTransaction')result=saveTransaction_(r.payload||{});else if(r.action==='saveReceipt')result=saveReceipt_(r.payload||{});else throw Error('ไม่พบคำสั่ง');return json_({success:true,data:result});}finally{lock.releaseLock();}
}catch(err){return json_({success:false,code:/^(จำนวนเงิน|วันที่ไม่ถูกต้อง|บันทึกเงินที่รับ|ข้อความยาวเกิน 2000|รหัสคำขอ|กรุณากรอกชื่อนักเรียน|ยอดรับเงินสุทธิ|กรุณาเลือกหมวด|ประเภทรายการ|เลขอ้างอิง BR-)/.test(err.message)?'VALIDATION_ERROR':'RETRY_OR_REVIEW',message:err.message});}}
function table_(id,name,required,extend){const s=SpreadsheetApp.openById(id).getSheetByName(name);if(!s)throw Error('ไม่พบชีต '+name);let h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0].map(x=>String(x).trim());required.forEach(k=>{if(!h.includes(k)){if(!extend)throw Error('ไม่พบคอลัมน์ '+k);if(h.length>=s.getMaxColumns())s.insertColumnsAfter(s.getMaxColumns(),1);s.getRange(1,h.length+1).setValue(k);h.push(k);}});return {s,h};}
function read_(id,name,required){const {s,h}=table_(id,name,required,false);if(s.getLastRow()<2)return [];return s.getRange(2,1,s.getLastRow()-1,h.length).getValues().map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>{if(k)o[k]=r[j] instanceof Date?Utilities.formatDate(r[j],'Asia/Bangkok',k==='date'||k==='ReceiptDate'?'yyyy-MM-dd':"yyyy-MM-dd'T'HH:mm:ssXXX"):r[j];});return o;}).filter(r=>name==='Transactions'?r.id:r.ReceiptNo);}
function write_(id,name,headers,obj,row){const {s,h}=table_(id,name,headers,true);const values=h.map(k=>obj[k]??'');if(values.some(v=>typeof v==='string'&&v.length>45000))throw Error('ประวัติรายการยาวเกินขนาดที่รองรับ');const target=row||s.getLastRow()+1;if(target>s.getMaxRows())s.insertRowsAfter(s.getMaxRows(),target-s.getMaxRows());if(row){const old=s.getRange(row,1,1,h.length).getValues()[0];h.forEach((k,j)=>{if(!(k in obj))values[j]=old[j];});}if(s.getRange(target,1,1,h.length).getFormulas()[0].some(Boolean))throw Error('รายการนี้มีสูตร กรุณาตรวจสอบในชีต');s.getRange(target,1,1,h.length).setValues([values.map(v=>typeof v==='string'&&/^[=+@-]/.test(v)?"'"+v:v)]);SpreadsheetApp.flush();}
function text_(v){const s=String(v??'').trim();if(s.length>2000)throw Error('ข้อความยาวเกิน 2000 ตัวอักษร');return s;}
function date_(v){const s=text_(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||isNaN(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw Error('วันที่ไม่ถูกต้อง');if(s>Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd'))throw Error('บันทึกเงินที่รับหรือจ่ายจริงได้ถึงวันนี้เท่านั้น');return s;}
function money_(v){if(v===''||v==null||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1e10)throw Error('จำนวนเงินไม่ถูกต้อง');return Math.round((Number(v)+Number.EPSILON)*100)/100;}
function id_(v){const s=text_(v);if(!/^[\w-]{8,100}$/.test(s))throw Error('รหัสคำขอไม่ถูกต้อง');return s;}
function saveTransaction_(p){const id=id_(p.id),rows=read_(FINANCE_DB,'Transactions',TX_HEADERS),old=rows.find(r=>r.id===id);if(old){if(old.reference&&String(old.reference).startsWith('BR-'))throw Error('รายการจากใบเสร็จไม่สามารถแก้ไขผ่านฟอร์มนี้');if(Number(p.revision)!==Number(old.revision)){if(!p.revision)return old;throw Error('รายการถูกแก้ไขแล้ว กรุณาโหลดใหม่');}if(!text_(p.reason))throw Error('กรุณาระบุเหตุผลแก้ไข');}
  if(!['income','expense'].includes(p.type))throw Error('ประเภทรายการไม่ถูกต้อง');const amount=money_(p.amount);if(amount<=0)throw Error('จำนวนเงินต้องมากกว่า 0');const category=text_(p.category);if(!category)throw Error('กรุณาเลือกหมวด');const now=new Date().toISOString(),record={date:date_(p.date),type:p.type,category,amount,note:text_(p.note),id,status:p.status==='void'?'void':'active',created_at:old?.created_at||now,updated_at:now,updated_by:'Boston Finance',payment_method:text_(p.payment_method),reference:text_(p.reference),attachment_url:old?.attachment_url||'',revision:Number(old?.revision||0)+1};
  if(!old&&record.reference.startsWith('BR-'))throw Error('เลขอ้างอิง BR- สงวนสำหรับใบเสร็จ');let history=[];try{history=JSON.parse(old?.history_json||'[]');}catch{throw Error('ประวัติเดิมไม่ถูกต้อง กรุณาตรวจสอบชีต');}history.push({at:now,action:old?'update':'create',reason:text_(p.reason),before:old?{date:old.date,type:old.type,category:old.category,amount:old.amount,status:old.status,note:old.note}:null,after:record});record.history_json=JSON.stringify(history);write_(FINANCE_DB,'Transactions',TX_HEADERS,record,old?._row);return record;}
function saveReceipt_(p){const request=id_(p.RequestID);table_(RECEIPT_DB,'Data1',RECEIPT_HEADERS,true);const rows=read_(RECEIPT_DB,'Data1',RECEIPT_HEADERS),existing=rows.find(r=>r.RequestID===request);let receipt=existing;
  if(!receipt){const student=text_(p.StudentName),course=text_(p.CourseLevel);if(!student||!course)throw Error('กรุณากรอกชื่อนักเรียนและหลักสูตร');const price=money_(p.CoursePrice),addon=money_(p.AddOnPrice),discount=money_(p.Discount),net=Math.round((price+addon-discount)*100)/100;if(net<=0)throw Error('ยอดรับเงินสุทธิต้องมากกว่า 0');const date=date_(p.ReceiptDate),year=date.slice(0,4),prefix='BR-'+year+'-N',max=rows.reduce((n,r)=>String(r.ReceiptNo).startsWith(prefix)?Math.max(n,Number(String(r.ReceiptNo).slice(prefix.length))||0):n,0);
    receipt={Timestamp:new Date().toISOString(),ReceiptNo:prefix+String(max+1).padStart(3,'0'),StudentName:student,ParentName:text_(p.ParentName),CourseLevel:course,CourseDetail:text_(p.CourseDetail),CoursePrice:price,AddOnItem:text_(p.AddOnItem),AddOnDetail:text_(p.AddOnDetail),AddOnPrice:addon,Discount:discount,NetTotal:net,ReceiptDate:date,Status:'ออกใบเสร็จแล้ว',RequestID:request,StudentID:text_(p.StudentID),EnrollmentID:text_(p.EnrollmentID),Level:text_(p.Level),PaymentMethod:text_(p.PaymentMethod),TransactionID:'RC-'+request};write_(RECEIPT_DB,'Data1',RECEIPT_HEADERS,receipt);
  }
  // Receipt is persisted first. A retry with the same RequestID repairs an interrupted second write.
  const tx=read_(FINANCE_DB,'Transactions',TX_HEADERS),linked=tx.filter(r=>r.reference===receipt.ReceiptNo||r.id===receipt.TransactionID);if(linked.length>1)throw Error('พบรายรับซ้ำสำหรับใบเสร็จนี้ กรุณาตรวจสอบก่อน');if(linked.length){const r=linked[0];if(r.type!=='income'||r.status!=='active'||money_(r.amount)!==money_(receipt.NetTotal))throw Error('รายรับที่เชื่อมไว้ไม่ตรงกับใบเสร็จ กรุณาตรวจสอบ');return receipt;}
  const now=new Date().toISOString(),record={date:receipt.ReceiptDate,type:'income',category:'income_course',amount:receipt.NetTotal,note:receipt.StudentName+' • '+receipt.CourseLevel,id:receipt.TransactionID,status:'active',created_at:now,updated_at:now,updated_by:'receipt',payment_method:receipt.PaymentMethod,reference:receipt.ReceiptNo,attachment_url:'',revision:1,history_json:JSON.stringify([{at:now,action:'receipt',reference:receipt.ReceiptNo}])};write_(FINANCE_DB,'Transactions',TX_HEADERS,record);return receipt;
}
